# This workflow will build a package using Maven

name: build

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B compile --file pom.xml
    # - name: Generate javadocs with Maven
    #   run: mvn javadoc:javadoc
