# This workflow will create javadocs and deploy to GitHub pages

name: publish-javadocs

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
  workflow_dispatch: #add this option for testing

jobs:
  publish-javadocs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Generate javadocs with Maven
      run: mvn javadoc:javadoc
    - name: Publish javadocs to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: ${GITHUB_HEAD_REF#refs/heads/}
        folder: target/site/apidocs
        target-folder: docs
