# This workflow will create javadocs and deploy to GitHub pages

name: publish-javadocs

on:
  push:
    branches:
      - master

jobs:
  publish-javadocs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Generate javadocs with Maven
      run: mvn javadoc:javadoc
    - name: Publish javadocs to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: master
        folder: target/site/apidocs
        target-folder: docs
        token: ${{ secrets.JAVADOCS_CI_TOKEN }}
